// export const API_URL = "https://frozen-taiga-15187.herokuapp.com/api/v1"
// export const API_URL = "https://panicky-toad-sheath-dress.cyclic.app/api/v1"
export const API_URL = "https://amused-peplum-boa.cyclic.app/api/v1"
// export const API_URL = "https://asaanmed-new-backend.vercel.app/api/v1"
// export const API_URL = "http://10.0.2.2:4000/api/v1"